config/routes.rb
Rails.application.routes.draw do
  get 'restaurants/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  get '/search', to: 'pages#search'
  get '/pending_orders', to: 'orders#pending_orders', as: 'pending'

  resources :restaurants, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 1 - I want a page with the list of all the products,
  # with buttons so that the user can add to cart
  # meals/meal_id/order_item

  resources :meals do
    resources :reviews, only: [:new, :create ]
    resources :order_items, only: [:create]

    collection do
      get '/owned', to: 'meals#owned'
    end
  end

  resources :reviews, only: [:destroy]

  resources :order_items, only: [:destroy]
  # 2 - When the user clicks on add to cart, I want to
  # create a order_item and and a list of orders and update the status
  # yet
  resources :orders, only: [:show, :index, :update]
  resources :seller_orders, only: [:show, :index, :update]
  resources :delivery_schedules, only: [:index, :new, :create, :destroy]


end

app/controllers/seller_orders_controller.rb
class SellerOrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    authorize @order, :seller_show?

  end

  def index
    @orders = Order.includes(:order_items).where(order_items: {
      meal_id: current_user.meals.ids
    }, status: ["pending", "approved"])
    authorize @orders, :seller_index?
  end

  def update
    @order = Order.find(params[:id])
    authorize @order, :seller_update?
    if ["approved", "cancelled"].include?(params[:status])
      @order.update(status: params[:status])
      redirect_to seller_orders_path
    else
      redirect_to seller_orders_path, alert: "Something went wrong"
    end

  end

  private
  def order_params
    params.require(:order).permit(:total_price, :status)
  end
end

app/views/seller_orders/index.html.erb
<!-- index action: seller_orders controler -->

<div class="container">
<h4>Your orders</h4>
  <div class="seller-orders">

<% if @orders.any? %>


  <% @orders.each do |order| %>

   <h4> Order #<%= order.id %>

<span class="badge badge-success"><%= order.status %></span>
   </h4>
    <ul>

      <% order.order_items.each do |order_item| %>
        <li> <%= "Ordered item: #{order_item.meal.name}, price/item: #{order_item.unit_price}, quantity: #{order_item.quantity}, total price: #{order_item.unit_price * order_item.quantity} " %> </li>
      <% end %>

    </ul>
    <ul>
      <li>
      <p> <%= "Customer address: #{order.user.address}, name: #{order.user.name},
         phone number: #{order.user.phone_number}, email: #{order.user.email}, order date: #{order.updated_at}"%> </p>
      <% if order.status == "pending" %>

        <%= link_to "Confirm", seller_order_path(order, status: "approved"), method: :patch, class: "btn btn-flat btn-primary" %>
        <%= link_to "Cancel", seller_order_path(order, status: "cancelled"), method: :patch, class: "btn btn-flat btn-danger" %>
      <% end %>
    </li>
    </ul>
  <% end %>
<% end %>
  </div>


<% if @orders.empty? %>
<h4> No orders were made for you yet! </h4>
<% end %>
</div>