config/routes.rb
Rails.application.routes.draw do
  get 'restaurants/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  get '/search', to: 'pages#search'
  get '/pending_orders', to: 'orders#pending_orders', as: 'pending'

  resources :restaurants, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 1 - I want a page with the list of all the products,
  # with buttons so that the user can add to cart
  # meals/meal_id/order_item

  resources :meals do
    resources :reviews, only: [:new, :create ]
    resources :order_items, only: [:create]

    collection do
      get '/owned', to: 'meals#owned'
    end
  end

  resources :reviews, only: [:destroy]

  resources :order_items, only: [:destroy]
  # 2 - When the user clicks on add to cart, I want to
  # create a order_item and and a list of orders and update the status
  # yet
  resources :orders, only: [:show, :index, :update]
  resources :seller_orders, only: [:show, :index, :update]
  resources :delivery_schedules, only: [:index, :new, :create, :destroy]


end

app/views/shared/_footer.html.erb
<div class="mt-3 footer-container">
  <div class="footer container">
<!-- https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer -->
    <div class="copyright">
      <small>Copyright 2020 SafeFood©</small>
    </div>

    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook-f"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <%= link_to image_tag("Left.jpg", alt: "logo"), '/', class: 'navbar-brand' %>
    <%= link_to root_path, class: "navbar-brand" do %>
    <% end %>

    <% if !user_signed_in? %>
      <div >
        <%= link_to "Login", new_user_session_path, class: "btn btn-outline-secondary align-items-end" %>
      </div>

    <% else %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


    <%# if user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <!-- Delivery schedules are hidded -->
        <!-- <li class="nav-item">
        <%#= link_to "Check your delivery schedules", delivery_schedules_path, class: "nav-link" if current_user.seller? %>
        </li>-->

        <li>
              <!-- # <a href="/meals/new">  create a new meal </a> -->
          <%= link_to "Sell your meal", new_meal_path, class: "nav-link" if current_user.seller? %>
        </li>
        <li>
          <!-- orders check-->
          <%= link_to "Check your orders", seller_orders_path, class: "nav-link" if current_user.seller? %>
        </li>
        <li>
          <!-- orders check for buyer-->
          <%= link_to "Ordered items", pending_path, class: "nav-link" if !current_user.seller? %>
        </li>

        <li class="nav-item">
          <%= link_to "Owned meals", owned_meals_path, class: "nav-link" if current_user.seller? %>
        </li>

        <li class="nav-item">
          <%= link_to "Account", edit_user_registration_path, method: :get, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>


      </ul>
    </div>
     <% end %>
  </div>
</div>