config/routes.rb
Rails.application.routes.draw do
  get 'restaurants/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  get '/search', to: 'pages#search'
  get '/pending_orders', to: 'orders#pending_orders', as: 'pending'

  resources :restaurants, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 1 - I want a page with the list of all the products,
  # with buttons so that the user can add to cart
  # meals/meal_id/order_item

  resources :meals do
    resources :reviews, only: [:new, :create ]
    resources :order_items, only: [:create]

    collection do
      get '/owned', to: 'meals#owned'
    end
  end

  resources :reviews, only: [:destroy]

  resources :order_items, only: [:destroy]
  # 2 - When the user clicks on add to cart, I want to
  # create a order_item and and a list of orders and update the status
  # yet
  resources :orders, only: [:show, :index, :update]
  resources :seller_orders, only: [:show, :index, :update]
  resources :delivery_schedules, only: [:index, :new, :create, :destroy]


end

app/views/pages/home.html.erb
<%# <div class="layout-background"> %>




<div class="container">

  <div class="text-center mt-3">
    <h1 class="h5 pb-3"> Olá! Qual é a sua restrição? </h1>
  </div>


  <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
   <!-- <div class="search-form-control form-group"> -->
      <!-- <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Discover restricted food nearby" /> -->
    <div class="card-categories">
<!--
      <div class="form-inline">
      <%= form_tag search_path, method: :get do %>

        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a name"
        %>
        <%= submit_tag "Search", class: "btn btn-secondary" %>

      <% end %>
      </div>
-->
      <div class="btn veg-pic image-center">
        <%= link_to search_path(restriction: "vegan"), class: "btn-label" do %>
        <% end %>
        <p> Vegan </p>
        <!-- <button name="vegan" type="submit"> Vegan > </button> -->
      </div>

      <div class="btn cel-pic image-center">
        <%= link_to search_path(restriction: "celiac"), class: "btn-label" do %>
        <% end %>
        <p> Celíaca </p>
        <!-- <button name="vegan" type="submit"> Vegan > </button> -->
      </div>

      <div class="btn dia-pic image-center">
        <%= link_to search_path(restriction: "diabetic"), class: "btn-label" do %>
        <% end %>
        <p> Diabetes </p>
        <!-- <button name="vegan" type="submit"> Vegan > </button> -->
      </div>

    </div>

  </form>


<%# </div> %>
<!-- the list of movies -->





<!-- A grid for the cards-meals # :
# filter by name on controller
# hidden tag in view, to store restriction
# controller action works with both of the filter-->

<!--
 <div class="cards-meals">
    <%# @meals.each do |meal|%>
      <%#= link_to meal_path(meal) do %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%#= cl_image_path meal.photo.key %>')">
          <h6> <b><%#="#{meal.user.name}: "%></b> <%#="#{meal.name} at #{meal.offer_price}$"%> </h6>
        </div>
      <%# end %>
    <%# end %>

  </div>
-->
</div>

app/views/pages/search.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col">



      <%unless user_signed_in?%>
        <h1 class="h4 pt-3 pb-0 text-center">Browse through our wonderful selection of foods!</h1>

      <%end%>

      <div class="my-3">
        <%= form_tag search_path, method: :get do %>

          <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a name"
          %>

          <%= hidden_field_tag :restriction, params[:restriction]

          %>

          <%= submit_tag "Search", class: "btn btn-block btn-success mt-1", style: "color: white" %>

        <% end %>
      </div>

        <% if @restaurants.length > 0 %>
        <p>Your meal can be found in one of this restaurants:</p>
          <% @restaurants&.each do |restaurant| %>
            <%= link_to restaurant_path(restaurant, restriction: params[:restriction]), class: "card-product" do %>
              <div class="card-product-image">
                <% if restaurant.photo.present? %>
                  <%= cl_image_tag(restaurant.photo.key) %>
                <% else %>
                  <img class="rounded-circle" src="http://placehold.it/100x100?text=no photo" alt="default photo">
                <% end %>
              </div>
              <div class="card-product-infos">
                <h2><%= restaurant.name %></h2>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <h6> OPS! No restaurant found: search again! :) </h6>
        <% end  %>

      </div>


    </div>
  </div>


</div>