config/routes.rb
Rails.application.routes.draw do
  get 'restaurants/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  get '/search', to: 'pages#search'
  get '/pending_orders', to: 'orders#pending_orders', as: 'pending'

  resources :restaurants, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 1 - I want a page with the list of all the products,
  # with buttons so that the user can add to cart
  # meals/meal_id/order_item

  resources :meals do
    resources :reviews, only: [:new, :create ]
    resources :order_items, only: [:create]

    collection do
      get '/owned', to: 'meals#owned'
    end
  end

  resources :reviews, only: [:destroy]

  resources :order_items, only: [:destroy]
  # 2 - When the user clicks on add to cart, I want to
  # create a order_item and and a list of orders and update the status
  # yet
  resources :orders, only: [:show, :index, :update]
  resources :seller_orders, only: [:show, :index, :update]
  resources :delivery_schedules, only: [:index, :new, :create, :destroy]


end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :reviews, dependent: :destroy
  validates :description, presence: true
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :show, :index ]
  def new
    @meal = Meal.new
    authorize @meal
  end

  def create
    @meal = Meal.new(meal_params)
    authorize @meal
    @meal.user = current_user  # current logged at the current moment - helper from rails
    # authorize @meal  # pundit
    if @meal.save
      redirect_to @meal, notice: 'Your meal was successfully created.' # this refers to the show @meal
    else
      render :new
    end
  end

 # owner meals
  def owned
    @meals = policy_scope(Meal).where(user_id: current_user.id)

  end

  # read
  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
    authorize @meal
  end

  # update
  def edit
    @meal = Meal.find(params[:id])
    authorize @meal
    # is OK to get error in development-pundit
  end

  def update
    @meal = Meal.find(params[:id])
    authorize @meal
    if @meal.update(meal_params)
      redirect_to meal_path(@meal), notice: 'Your meal was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @meal = Meal.find(params[:id])
    authorize @meal
    @meal.destroy
    redirect_to orders_path
  end

  private
  def meal_params
    params.require(:meal).permit(:name, :offer_price, :description, :restriction, :photo)
  end

end

app/views/meals/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
     <div class="col col-lg-4">

       <div class="signup-card">
         <%= simple_form_for meal do |f| %>

            <%= f.input :name %>
            <%= f.input :offer_price %>
            <%= f.input :description %>
            <%= f.input :restriction %>
            <%= f.input :photo, as: :file, class:"btn-buzz" %>

       <div class="form-actions green-button">
         <%= f.button :submit, class: "btn btn-flat" %>
         <%= link_to "Back to meals", meals_path, class: "btn btn-outline-secondary mt-3 w-100" %>
       </div>

       <% end %>
       </div>
     </div>
   </div>
</div>

app/views/meals/edit.html.erb
<div class="container" style="margin-bottom: 50px">

  <h1 class="text-center title">Add a new meal</h1>

  <%= render 'form', meal: @meal %>

  <%= link_to "back to meals", meals_path%>

</div>

app/views/meals/index.html.erb
<div class="container" style="margin-bottom: 50px">
  <%unless user_signed_in?%>
  <h1 class="text-center call-to-action">Browse through our wonderful selection of foods!</h1>
  <%end%>
  <div class="cards">
    <% @meals.each do |meal| %>
      <%= link_to meal do %>
        <div class="card-meal">
         <%= cl_image_tag(meal.photo.key) %>   <!-- check the comment down and see where u can replace-->
          <div class="card-meal-infos">
            <div>
              <h2 class="card-meal-pricing">$ <%= meal.offer_price %></h2>
              <h2><%= meal.name %></h2>
              <h2><%= meal.description %></h2>
              <h2><%= meal.restriction %></h2>
              <!-- #cloudinary photo can be put here alternatively check it out --> 
            </div>
            <div class="card-meal-user">
              <p><em><%= meal.user.name %></em></p>
              <p><em><%= meal.user.phone_number %></em></p>
              <p><em><%= meal.user.email %></em></p>
              <p><em><%= meal.user.address %></em></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/meals/new.html.erb
<div class="container" style="margin-bottom: 50px">

  <h1 class="text-center title">Add a new meal</h1>

  <%= render 'form', meal: @meal %>



</div>

app/views/meals/owned.html.erb
<div style="margin-bottom: 50px">
  <div class="restaurant-banner text-center p-3 bg-light mb-3 mt-3">
    <h1 class="h3 pt-3 pb-0">Your meals</h1>
  </div>
  <%unless user_signed_in?%>
  <h1 class="text-center call-to-action">Browse through our wonderful selection of foods!</h1>
  <%end%>

  <div class="cards">
    <% @meals.each do |meal| %>
      <%= link_to meal, class: "card-product" do %>
        <div class="card-product-image">
          <%= cl_image_tag(meal.photo.key, crop: :fill, width: 100, height: 100) %>
        </div>  
        <div class="card-product-infos">
          <h2><%= meal.name %></h2>
          <p>$ <%= meal.offer_price %>,00 </p>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/meals/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col col-lg-6 p-0">
      <div class="pic-show">
        <%= cl_image_tag(@meal.photo.key) %>
      </div>
      <div class="card-body card-show">

        <h1 class="h3"> <%= @meal.name %> </h1>
        <p class="border-price h5 pb-2"> $<%= @meal.offer_price %>,00 </p>
        <p> <%= @meal.description %> </p>
        <p> <strong>Restriction: </strong><%= @meal.restriction %> </p>

        <% if current_user == @meal.user %>
          <% link_to "edit", edit_meal_path(@meal) %>
        <% end %>

        <% if current_user != @meal.user  %>
          <%= simple_form_for [@meal, OrderItem.new] do |f| %>
            <%= f.input :quantity, :input_html => { :value => 1, :min => 1 } %>
            <div class="green-button">
              <%= f.submit "Order" %>
            </div>
          <% end %>
        <% end %>
        <!-- Reviews "paths check"-->
        <div>
          <!-- <%= link_to 'Edit', edit_meal_path(@meal), class: "btn btn-outline-secondary mt-3 w-100" %> -->
          <!-- <%= link_to 'Back', restaurant_path(id: @meal.user.id, restriction: @meal.restriction), class: "btn btn-outline-secondary mt-3 w-100" %> -->
          <%= link_to 'Leave a review', new_meal_review_path(@meal), class: "btn btn-outline-secondary mt-3 w-100" %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Reviews-enrich show-->

<ul class="list-group">
  <% @meal.reviews.each do |review| %>
    <li class="list-group-item">
      <%= review.content %>
    </li>
  <% end %>
</ul>

<!-- Review destroy-->